---
title: "Presupuestos"
output: 
  pdf_document: default
always_allow_html: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, results = "asis")
#library(shiny)
#library(flexdashboard)
#setwd("../")
#source("global.R")

```

Desglose Presupuesto
============================================

### Grafico de barras
```{r, warning=FALSE}

  datos_treemap <- group_by_(datos_treemap, input$nivel) %>%
    dplyr::summarise(Monto = sum(Monto, na.rm=TRUE)) %>%
    arrange(desc(Monto)) %>%
    as.data.frame()
  
  highchart() %>%
    hc_chart(type = "column") %>%
    #hc_title(text = "Presupuesto por Grupo de Gasto") %>%
    hc_xAxis(categories = datos_treemap[,1]) %>%
    hc_add_series(data = datos_treemap$Monto,
                  colorByPoint = TRUE,
                  name = "Monto")


```

### Tabla
```{r, warning=FALSE}
datos_treemap <- group_by_(datos_treemap, input$nivel) %>%
    dplyr::summarise(Monto = sum(Monto, na.rm=TRUE)) %>%
    arrange(desc(Monto)) %>%
    as.data.frame()
  
  datatable(datos_treemap, extensions="Scroller", style="bootstrap", class="compact", width="100%",
            options=list(dom="t",deferRender=TRUE, scroller=FALSE)) %>%
    formatCurrency(c(2)) %>% 
    formatStyle(c(0), target='row', fontSize = '80%')
  

```

### Treemap
```{r, warning=FALSE}

  datos_treemap <- group_by_(datos_treemap, input$nivel) %>%
    dplyr::summarise(Monto = sum(Monto, na.rm=TRUE)) %>%
    arrange(desc(Monto)) %>%
    as.data.frame()
  
  tm <- treemap(datos_treemap, index = c(input$nivel),
                vSize = "Monto", vColor = input$nivel,
                type = "index",
                draw = FALSE)
  
  highchart() %>% 
    hc_add_series_treemap(tm, allowDrillToNode = TRUE,
                          layoutAlgorithm = "squarified") %>% 
    hc_title(text = "Presupuestos") %>% 
    hc_tooltip(pointFormat = "<b>{point.name}</b>:<br>
               Programa: {point.:,.0f}<br>
               Monto: {point.value:,.0f}")
  

```

Origen y Destino Gastos
============================================

### Sankey Diagram
```{r, warning=FALSE}

  sankeyNetwork(Links = datos_sankey$datos, Nodes = datos_sankey$nodes, Source = "source",
                Target = "target", Value = "value", NodeID = "name",
                units = "$", fontSize = 12, nodeWidth = 30, sinksRight = TRUE)
  

```
