---
title: "Presupuestos"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny    
---

```{r setup, include=FALSE}
library(shiny)
library(flexdashboard)
source("global.R")

```

Column 
-----------------------------------------------------------------------

### Arbol de navegacion

```{r}
# UI
fluidPage(
    fluidRow(
      column(7,
             uiOutput("Hierarchy"),
             #verbatimTextOutput("results"),
             #tableOutput("clickView"),
             d3treeOutput(outputId="d3",width = '1200px',height = '800px')
      ),
      column(5,
             dataTableOutput('table')
      )
    )
  )

# SERVER
#SearchTree----
  
  output$Hierarchy <- renderUI({
    Hierarchy=names(m)
    Hierarchy=head(Hierarchy,-1)
    selectizeInput("Hierarchy","Tree Hierarchy",
                   choices = Hierarchy,multiple=T,selected = Hierarchy,
                   options=list(plugins=list('drag_drop','remove_button')))
  })
  
  network <- reactiveValues()
  
  observeEvent(input$d3_update,{
    network$nodes <- unlist(input$d3_update$.nodesData)
    activeNode<-input$d3_update$.activeNode
    if(!is.null(activeNode)) network$click <- jsonlite::fromJSON(activeNode)
  })
  
  observeEvent(network$click,{
    output$clickView<-renderTable({
      as.data.frame(network$click)},
      caption='Last Clicked Node',caption.placement='top')
  })
  
  
  TreeStruct=eventReactive(network$nodes,{
    df=m
    if(is.null(network$nodes)){
      df=m
    }else{
      
      x.filter=tree.filter(network$nodes,m)
      df=ddply(x.filter,.(ID),function(a.x){m%>%filter_(.dots = list(a.x$FILTER))%>%distinct})
    }
    df
  })
  
  observeEvent(input$Hierarchy,{
    output$d3 <- renderD3tree({
      if(is.null(input$Hierarchy)){
        p <- m
      }else{
        p=m%>%select(one_of(c(input$Hierarchy,"NEWCOL")))%>%unique
        #p <- select_(m, c(input$Hierarchy),"NEWCOL") %>% distinct(.keep_all=TRUE)
      }
      
      d3tree(data = list(root = df2tree(struct = p,rootname = 'Presupuestos'), layout = 'collapse'),
             activeReturn = c('name','value','depth','id'),
            height = 18)
    })
  })
  
  observeEvent(network$nodes,{
    output$results <- renderPrint({
      str.out=''
      if(!is.null(network$nodes)) str.out=tree.filter(network$nodes,m)
      return(str.out)
    })    
  })
  
  output$table <- renderDataTable(expr = {
    datatable(TreeStruct() %>% select(-NEWCOL),extensions="Scroller", style="bootstrap", class="compact", width="800%",
    options=list(deferRender=FALSE, scrollY=600, scroller=TRUE))
  })

```
